sudo: false
before_install:
  - npm install -g npm@latest
language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
script:
  - npm run test
after_success:
  - curl -Lo travis_after_all.py https://raw.githubusercontent.com/contentful/travis_after_all/master/travis_after_all.py
  - python travis_after_all.py
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
